In [1]:
import numpy as np
from numpy import *

# Create Array

In [3]:
arr=array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [4]:
arr=array([1,2,3,4.5,6])
print(arr)
print(arr.dtype)

[1.  2.  3.  4.5 6. ]
float64


In [5]:
arr=array([1,2,3,4.5,5,6],int)
print(arr)
print(arr.dtype)

[1 2 3 4 5 6]
int32


# Create Array With Linespace

In [7]:
arr=linspace(0,10)
print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [8]:
arr=linspace(0,10,12)
arr

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [9]:
arr=linspace(0,10,10)
print(arr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [10]:
arr=linspace(0,10,11)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Numpy array using arrange

In [11]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [12]:
arr=np.arange(1,15,3)
print(arr)

[ 1  4  7 10 13]


# Numpy Array Using Logspace

In [13]:
arr=logspace(1,10,5)   #log10 2
print(arr)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [14]:
print(arr[0])

10.0


In [18]:
print('%.2f',%arr[0])

SyntaxError: invalid syntax (<ipython-input-18-f6542c97aa7b>, line 1)

# numpy using zero

In [23]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [25]:
arr=zeros(10,int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [27]:
arr=zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
arr=zeros((4,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
arr=zeros((4,3,2),int)
print(arr)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


# Numpy Array From List

In [31]:
list=[1,2,3,4,5]
arr=array(list)
print(arr)

[1 2 3 4 5]


In [32]:
list=[[1,2,3],[4,5,6]]
arr=array(list)
print(arr)

[[1 2 3]
 [4 5 6]]


In [34]:
list=[[1,2,3],[4,5]]
arr=np.array(list)
print(arr)

[list([1, 2, 3]) list([4, 5])]


<ipython-input-34-106317d8262e>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr=np.array(list)


In [36]:
list=[[1,2,3],[4,5,6],[6,7]]
arr=array(list)
print(arr)

[list([1, 2, 3]) list([4, 5, 6]) list([6, 7])]


<ipython-input-36-cd2bf49739b8>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr=array(list)


In [37]:
list=[[1,2,3],[4,5,6],[6,7,8]]
arr=array(list)
print(arr)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


# Create Matrix

In [42]:
matrix=np.full(5,10)
print(matrix)

[10 10 10 10 10]


In [46]:
matrix=full((4,3),5)
print(matrix)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [49]:
matrix=eye(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
matrix=diag([4,5,3])
matrix

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 3]])