In [1]:
import numpy as np
from numpy import *

In [2]:
arr1=array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr2=array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr4=arr1.sum(axis=1) #summation of row
print(arr)

[ 6 15 24]


In [21]:
arr5=arr1.sum(axis=0) #summation of coloum
print(arr5)

[12 15 18]


In [22]:
a=sum(arr4)#sumation the array
print(a)

45


In [24]:
b=add(arr4,arr5)#sumation of 2 array
print(b)

[18 30 42]
