In [1]:
import numpy as np
from numpy import *

In [7]:
arr=array([[1,2,3],[3,4,5],[6,7,8],[7,9,8],[7,9,0]])
print(arr)

[[1 2 3]
 [3 4 5]
 [6 7 8]
 [7 9 8]
 [7 9 0]]


In [8]:
arr1=arr[:2,:2]
print(arr1)

[[1 2]
 [3 4]]


In [9]:
bool_e=arr>3
print(bool_e)

[[False False False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True False]]


In [10]:
arr1=arr[1:4,1:]
print(arr1)

[[4 5]
 [7 8]
 [9 8]]
