In [3]:
import numpy as np
from numpy import *

In [4]:
arr=linspace(1,15,15)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [6]:
for i in arr:
    print(int(i),end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [7]:
for i in range(len(arr)):
    print(int(arr[i]),end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [8]:
print(arr[2:6])

[3. 4. 5. 6.]


In [9]:
print(arr[:6])

[1. 2. 3. 4. 5. 6.]


In [10]:
print(arr[5:])

[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [11]:
arr1=arr.copy
arr1

<function ndarray.copy>