In [1]:
import numpy as np
from numpy import *

# Random generation in numpy

In [2]:
arr=np.random.rand(5)
print(arr)

[0.05999338 0.30243101 0.81408551 0.74677395 0.54093624]


In [3]:
arr=random.rand(3,4)
print(arr)

[[0.80222575 0.03978338 0.7532259  0.64688303]
 [0.0936529  0.30163816 0.01704948 0.85866529]
 [0.77213213 0.41196008 0.69329567 0.74158632]]


In [4]:
arr=random.rand(3,4,5)
print(arr)

[[[0.9642184  0.06540489 0.35011729 0.35891133 0.83204257]
  [0.56067245 0.27119955 0.55489802 0.68290312 0.91767474]
  [0.24346099 0.88524255 0.32953131 0.97733751 0.03415085]
  [0.49274857 0.14504177 0.31035673 0.81814455 0.45114592]]

 [[0.47508144 0.89879527 0.70863627 0.04664098 0.27543068]
  [0.26858727 0.51585817 0.18386556 0.47413534 0.44652174]
  [0.21912768 0.22921801 0.24796358 0.50481855 0.65408964]
  [0.82969311 0.38484052 0.11587221 0.31005916 0.03230908]]

 [[0.25006024 0.60285739 0.4665943  0.48098777 0.38635478]
  [0.30710646 0.73868216 0.75766966 0.94562614 0.6167621 ]
  [0.13733801 0.89401356 0.6036628  0.58048112 0.38932475]
  [0.55078512 0.60114455 0.39971133 0.20116405 0.96287271]]]


In [5]:
arr=random.randn(5)
print(arr)

[ 1.4114931   0.42116103 -0.03481198 -1.04023681  0.57706693]


In [6]:
arr=random.randn(3,4)
print(arr)

[[ 0.54194986  0.90352107 -0.1513618   1.07396486]
 [ 1.14611406  1.59490117  1.0714444   1.21989468]
 [-0.71098441 -0.35779339 -1.72366321  0.92775748]]


In [13]:
arr=np.random.randint(1,11,5)
print(arr)

[4 5 7 5 1]


In [14]:
arr=np.random.randint(1,11,5)
print(arr)

[7 5 8 5 7]


In [16]:
arr=random.randint(1,15,(4,6))
print(arr)

[[ 6  9  4  7  3  6]
 [12 11  1 10 11 13]
 [11  3 13  8  9  4]
 [ 6  6  3 10  1 13]]


In [18]:
arr=random.randint(1,11,(3,4,5))
print(arr)

[[[ 1  4  1  4  7]
  [ 9  8  2  3  2]
  [ 4  6  8  8  3]
  [ 6  8  6  7  5]]

 [[ 3  6  5  4 10]
  [10  8  4  2  2]
  [ 7  8  3  6  2]
  [ 6  6  3  6  9]]

 [[ 8 10  4  1  8]
  [ 3  1  8  1  6]
  [ 8  3  1  8  7]
  [ 3  1  6  2 10]]]
