In [1]:
import numpy as np
from numpy import *

In [5]:
arr1=np.ones((3,4),int)
print(arr1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
arr2=arr1.reshape(6,2)
print(arr2)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [8]:
arr3=arr2.ravel()
print(arr3)

[1 1 1 1 1 1 1 1 1 1 1 1]


In [10]:
arr4=np.full((3,4),5)
print(arr4)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [11]:
arr5=arr4.ravel()
arr5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
arr3+arr5


array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])