In [1]:
import numpy as np
from numpy import *

In [3]:
arr1=linspace(0,15,16)
print(arr1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [15]:
arr2=ones((3,4),int)
print(arr2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
arr1.ndim

1

In [6]:
arr2.ndim

2

In [7]:
arr1.shape

(16,)

In [8]:
arr2.shape

(3, 4)

In [9]:
arr1.size

16

In [10]:
arr2.size

12

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
arr1.data

In [14]:
arr2.data